# Generated by Django 5.2.7 on 2025-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("NIT", "NIT"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "nombre_razon_social",
                    models.CharField(
                        max_length=255, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tercero",
                "verbose_name_plural": "Terceros",
                "ordering": ["nombre_razon_social"],
            },
        ),
    ]
