# Generated by Django 5.2.7 on 2025-10-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("terceros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("emitida", "Emitida"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                (
                    "cufe",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="CUFE",
                    ),
                ),
                (
                    "qr_code",
                    models.TextField(blank=True, null=True, verbose_name="Código QR"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="terceros.tercero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "impuesto_porcentaje",
                    models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Factura",
                "verbose_name_plural": "Ítems de Factura",
            },
        ),
    ]
