# Generated by Django 5.2.7 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemfactura",
            name="impuesto_porcentaje",
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="lleva_iva",
            field=models.BooleanField(default=True, verbose_name="¿Lleva IVA?"),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="subtotal_linea",
            field=models.DecimalField(
                decimal_places=2, help_text="Subtotal antes de impuestos", max_digits=15
            ),
        ),
    ]
