# Generated by Django 5.2.7 on 2025-10-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("terceros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Asiento")),
                ("concepto", models.CharField(max_length=500, verbose_name="Concepto")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Adicional"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tercero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="terceros.tercero",
                        verbose_name="Tercero Involucrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Cuenta"
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="contabilidad.cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Plan de Cuentas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Débito",
                    ),
                ),
                (
                    "credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédito",
                    ),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="contabilidad.asientocontable",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad.cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
                "ordering": ["asiento", "id"],
            },
        ),
    ]
