# Generated by Django 5.2.7 on 2025-10-19 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_asientocontable_descripcion_adicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='ajusta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='contabilidad.asientocontable'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='anulacion_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='vigente', max_length=10),
        ),
    ]
