# Generated by Django 5.2.7 on 2025-10-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_periodocontable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodocontable',
            options={},
        ),
        migrations.RenameField(
            model_name='periodocontable',
            old_name='ventana_enero_marzo',
            new_name='habilitar_mes13',
        ),
        migrations.RemoveField(
            model_name='periodocontable',
            name='cerrado_en',
        ),
        migrations.RemoveField(
            model_name='periodocontable',
            name='cerrado_por',
        ),
        migrations.RemoveField(
            model_name='periodocontable',
            name='notas',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='fiscal_period',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='fiscal_year',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='ajustes_fin',
            field=models.DateField(default='2026-03-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='ajustes_inicio',
            field=models.DateField(default='2026-03-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='requiere_pins_en_ajustes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cierre', 'En Cierre'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
    ]